sudo: required
language: minimal

matrix:
  include:

    - os: linux
      services:
        - docker
      script:
        - ./run-in-docker.sh make dep install test

deploy:
  skip_cleanup: true
  provider: script
  script: ./run-release.sh $TRAVIS_TAG
  on:
    tags: true
