sudo: required
language: minimal

env:
  global:
    - GOVERSION=1.12.1
    - GOMETALINTER_VERSION=2.0.11
    - GITHUB_RELEASE_VERSION=0.7.2

matrix:
  include:

    - os: linux
      services:
        - docker
      script:
        - ./run-in-docker.sh make dep install test

    - os: osx
      osx_image: xcode10.1
      before_install:
        # v8 prebuilt library
        - git clone https://github.com/jkcfg/prebuilt.git
        - make -C prebuilt install
        # go
        - (cd ~ && curl -fsSLO https://dl.google.com/go/go${GOVERSION}.darwin-amd64.tar.gz)
        - mkdir ~/go-${GOVERSION} && tar xf ~/go${GOVERSION}.darwin-amd64.tar.gz -C ~/go-${GOVERSION} --strip-components 1
        # gometalinter
        - (cd ~ && curl -fsSLO https://github.com/alecthomas/gometalinter/releases/download/v${GOMETALINTER_VERSION}/gometalinter-${GOMETALINTER_VERSION}-darwin-amd64.tar.gz)
        - tar -xf ~/gometalinter-${GOMETALINTER_VERSION}-darwin-amd64.tar.gz -C /usr/local/bin --strip-components 1
        # github-release
        - (cd ~ && curl -fsSLO https://github.com/aktau/github-release/releases/download/v${GITHUB_RELEASE_VERSION}/darwin-amd64-github-release.tar.bz2)
        - tar -xf ~/darwin-amd64-github-release.tar.bz2 -C /usr/local/bin --strip-components 3
      script:
        - export PATH=~/go-${GOVERSION}/bin:~/go/bin:$PATH
        - make dep install test

deploy:
  skip_cleanup: true
  provider: script
  script: ./run-release.sh $TRAVIS_TAG
  on:
    tags: true
